# @package _group_
name: cifar10
cls: codes.dataset.${dataset.name}
dir: ${general.base_path}/data
dataloader:
  train:
    batch_size: 128
    shuffle: True
    num_workers: 2
  test:
    batch_size: 128
    shuffle: False
    num_workers: 2
